### PR TITLE
boring copy-editing

### PR DESCRIPTION
**Pull request by glaebhoerl**

### CODE REVIEW

**Comment by glaebhoerl** [comment]
One thing that looks wrong but I don't know how to fix it:

> ```
> BorrowedMut<&mut<'a, T>, T>>
> ```

Line 783.

There are too many closing angle brackets, but more importantly the first parameter of `BorrowedMut` is supposed to be a lifetime?

**Comment by Ericson2314** [comment]
OMG thanks you for this @glaebhoerl so much! It was getting very unwieldy to edit from length alone, and there's nothing like a second set of eyes to pick up what the first glosses over from repetition.

**Comment by Ericson2314** [comment]
~~[please don't delete branch just yet, I merged this wrong.]~~ resolved.

**Comment by Ericson2314** [comment]
And I fixed the second thing too; it's supposed to be:

```
BorrowedMut<'new, &mut<'old, T, T>>
```

Thanks again!

**Comment by glaebhoerl** [comment]
You're welcome!

N.B. I was mostly just paying attention to the prose because, while I'm more-or-less familiar with the syntax of judgments, deciphering them (and that's the right word) for me is still Work. Would you be interested in having more-familiar-syntax (and fewer-abbreviations) versions of them somewhere in the spirit of something like [this](https://github.com/rust-lang/rfcs/pull/1657#issuecomment-227827154) or [this](https://twitter.com/psygnisfive/status/721875119933624320) maybe? (Obviously it's a cultural issue, for many people the familiarity ordering is probably the reverse.)

**Pull request merged**
